# Project information
site_name: Mathy Envs
site_description: RL environments for manipulating math trees
site_author: Justin DuJardin
site_url: https://envs.mathy.ai

# Copyright
copyright: Copyright &copy; 2011 - 2023 Justin DuJardin

repo_name: mathy/mathy_envs
repo_url: https://github.com/mathy/mathy_envs
edit_uri: edit/master/website/docs/

google_analytics:
- UA-8701293-12
- auto

nav:
- Home: https://mathy.ai
- Core: https://core.mathy.ai
- Environments:
  - Home: index.md
  - Customization: customization.md
  - Observations: observations.md
  - API:
    - Env: api/env.md
    - Envs:
      - Binomial Distribute: api/envs/binomial_distribute.md
      - Complex Simplify: api/envs/complex_simplify.md
      - Poly Combine In Place: api/envs/poly_combine_in_place.md
      - Poly Commute Like Terms: api/envs/poly_commute_like_terms.md
      - Poly Grouping: api/envs/poly_grouping.md
      - Poly Haystack Like Terms: api/envs/poly_haystack_like_terms.md
      - Poly Simplify: api/envs/poly_simplify.md
      - Poly Simplify Blockers: api/envs/poly_simplify_blockers.md
    - State: api/state.md
    - Time Step: api/time_step.md
    - Util: api/util.md
  - Misc:
    - Releases: changelog.md
    - License: license.md
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/justindujardin
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/justindujardin
  - icon: fontawesome/brands/linkedin
    link: https://linkedin.com/in/justindujardin

extra_css:
- lib/styles.css

extra_javascript:
- lib/termynal.js

theme:
  name: material
  icon:
    logo: material/image
  features:
  - instant
  - navigation.tabs
  - navigation.sections
  - navigation.tabs.sticky
  - navigation.footer
  - navigation.top
  - content.action.edit
  - content.action.view
  - content.tooltips
  favicon: img/favicon/favicon-16x16.png
  palette:
    primary: green
    accent: lime
  highlightjs: true
  hljs_languages:
  - python
  - typescript
  - json
markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: true
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences
- pymdownx.details

plugins:
- mathy
- search
- social
- git-revision-date-localized
- git-committers
- minify:
    minify_html: true
